### ISSUE TITLE
Qemu build issues on Ubuntu 19

### ISSUE THREAD

**Issue by monik3r** [angr/phuzzer#4]
Hi,

There seems to be a problem with building QEMU while running Ubuntu 19 when setting up phuzzer. 

```  util/memfd.c:40:12: error: static declaration of ‘memfd_create’ follows non-static declaration
   static int memfd_create(const char *name, unsigned int flags)
              ^~~~~~~~~~~~
  In file included from /usr/include/x86_64-linux-gnu/bits/mman-linux.h:111:0,
                   from /usr/include/x86_64-linux-gnu/bits/mman.h:34,
                   from /usr/include/x86_64-linux-gnu/sys/mman.h:41,
                   from /tmp/pip-req-build-r26yq_bw/bin/afl-unix/qemu_mode/qemu-2.10.0/include/sysemu/os-posix.h:29,
                   from /tmp/pip-req-build-r26yq_bw/bin/afl-unix/qemu_mode/qemu-2.10.0/include/qemu/osdep.h:104,
                   from util/memfd.c:28:
  /usr/include/x86_64-linux-gnu/bits/mman-shared.h:50:5: note: previous declaration of ‘memfd_create’ was here
   int memfd_create (const char *__name, unsigned int __flags) __THROW;
       ^~~~~~~~~~~~
  make: *** [/tmp/pip-req-build-r26yq_bw/bin/afl-unix/qemu_mode/qemu-2.10.0/rules.mak:66: util/memfd.o] Error 1
```

I've tried downgrading gcc and etc to 6.0 (was using 8.4 before), and same issue. It might be related to a similar issue in Avatar2: https://github.com/avatartwo/avatar2/issues/14.

To maybe help diagnose this would it be possible to know what distro and kernel verion phuzzer is being developed with? Thanks!

**Comment by zardus** [comment]
We target all development to the latest LTS release of Ubuntu (18.04,
currently).

**Comment by monik3r** [comment]
Can confirm that Ubuntu 18.04 works, thanks

**Comment by mahaloz** [comment]
Hey this is still an issue in 20.04 LTS. Looking into a fix now.

**Comment by twizmwazin** [comment]
This issue seems to have to do with building the binaries for shellphish-afl and shellphish-qemu rather than the phuzzer package itself. This should be able to be bypassed by installing our wheels from the [angr/wheels](https://github.com/angr/wheels) repo. I was able to get phuzzer installed in a 20.04 docker container like this:

```
FROM ubuntu:focal

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/angr/angr-dev.git /root/angr-dev
WORKDIR /root/angr-dev

RUN DEBIAN_FRONTEND="noninteractive" ./setup.sh -i -u

RUN pip3 install https://github.com/angr/wheels/blob/master/shellphish_afl-1.2.1-py2.py3-none-manylinux1_x86_64.whl?raw=true
RUN pip3 install https://github.com/angr/wheels/blob/master/shellphish_qemu-0.10.0-py3-none-manylinux1_x86_64.whl?raw=true

RUN ./setup.sh -u phuzzer

RUN python3 -c "import phuzzer; print('it works')"
```

**Comment by SourceCodeDeleted** [comment]
While the instructions above help it doesn't seem to be a complete fix.

`python3 -m phuzzer -i -c 4 -d 2 /home/user/works/qemu/angr-dev/foo`

```
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 
'/home/user/.local/lib/python3.6/site-packages/shellphish_afl/../bin/afl-unix/afl-fuzz': '/home/user/.local/lib/python3.6/site-packages/shellphish_afl/../bin/afl-unix/afl-fuzz'
```

**Comment by twizmwazin** [comment]
This issue is related to shellphish-qemu and we have a workaround, so I'm going to consider this complete.
